### ISSUE TITLE
port 8080 not used by container

### ISSUE THREAD

**Issue by sahlex** [mlabouardy/hystrix-dashboard-docker#3]
According to the logs, tomcat starts on port 9002. After changing to 

```
docker run -d -p 8080:9002 --name hystrix-dashboard mlabouardy/hystrix-dashboard:latest
```

it worked perfectly.

**Comment by javafuns** [comment]
right, the internal server port in container is not 8080 but 9002.

**Comment by thiagoloureiro** [comment]
please don't forget to update Readme.MD :)

**Comment by mlabouardy** [comment]
fixed
